"use strict";
const professionsArray = [
    { value: "arts-craft-creatives", label: "Arts / Craft / Creatives" },
    { value: "automobile-services", label: "Automobile Services / Car Painting / Car Mechanic / Car Electrician / Car Panel Beater / Car Upholstery" },
    { value: "aviation-airline-services", label: "Aviation / Airline Services / Air Hostess / Pilot / Captain / Aircraft Engineer" },
    { value: "biological-sciences", label: "Biological Sciences - Biochemistry / Microbiology / Plant Science / Environmental" },
    { value: "caregiver-nanny", label: "Caregiver / Nanny / Domestic Help" },
    { value: "cashiers-tellers", label: "Cashiers / Tellers / Ticketing" },
    { value: "chaplain-pastoral", label: "Chaplain / Pastoral / Reverend / Ministration" },
    { value: "cleaning-janitorial", label: "Cleaning / Janitorial / Laundry" },
    { value: "computer", label: "Computer" },
    { value: "computer-cloud-computing", label: "Computer / Cloud Computing / Data Warehousing / Amazon Web Services (AWS)" },
    { value: "computer-database-admin", label: "Computer / Database Support / Database Admin / Database Development / Oracle / MySQL" },
    { value: "computer-frontend-design", label: "Computer / Frontend Design / UI / UX / Frontend Scripting / Javascript / React / JQuery" },
    { value: "computer-fullstack-dev", label: "Computer / Full Stack Software Development / Frontend & Backend / Web Design & Development" },
    { value: "computer-graphics-design", label: "Computer / Graphics Design / Artist" },
    { value: "computer-mobile-dev", label: "Computer / Mobile App Development / Android / IOS / Games / React Native / Flutter" },
    { value: "computer-network-engineering", label: "Computer / Network & Hardware Engineering Support / Network Design and Security" },
    { value: "computer-system-admin", label: "Computer / System Admin / Software Support / Windows Admin / Linux Admin" },
    { value: "consulting-business-strategy", label: "Consulting / Business Strategy / Planning" },
    { value: "cook-chef-baker", label: "Cook / Chef / Baker / Pastry Chef / Steward" },
    { value: "customer-service", label: "Customer Service / Call Centre / Front Desk / Receptionist" },
    { value: "data-entry-analysis", label: "Data Entry / Analysis" },
    { value: "digital-marketing", label: "Digital Marketing / Social Media Management" },
    { value: "driving-dispatch-rider", label: "Driving / Haulage / Dispatch Rider / Bike Rider / Chauffeur" },
    { value: "economics-statistics", label: "Economics / Statistics / Data Science" },
    { value: "education-higher-institution", label: "Education - Higher Institution / Teaching / Lecturing / Training" },
    { value: "education-non-academic", label: "Education - Non Academic / Registrar / Bursary / Admin / Librarian" },
    { value: "education-sec-pri", label: "Education - Sec/Pri/Creche / Teaching / Tutoring / Creche Services" },
    { value: "election-personnel", label: "Election Personnel / Ad-hoc Officers" },
    { value: "engineering", label: "Engineering" },
    { value: "engineering-biomedical", label: "Engineering - Biomedical Engineering" },
    { value: "engineering-chemical", label: "Engineering - Chemical / Petroleum / Petrochemical" },
    { value: "engineering-civil", label: "Engineering - Civil / Construction / Building" },
    { value: "engineering-electrical", label: "Engineering - Electrical / Electronics / Telecom" },
    { value: "engineering-mechanical", label: "Engineering - Mechanical / Metallurgical / Mechatronics" },
    { value: "environmental-services", label: "Environmental Services" },
    { value: "executive-management", label: "Executive / Top Management" },
    { value: "facility-estate-management", label: "Facility Management / Estate Management / Maintenance" },
    { value: "fashion-design", label: "Fashion Design / Beauty Care / Make-up / Tailoring / Hair Stylist" },
    { value: "finance-accounting", label: "Finance / Accounting / Audit / Tax" },
    { value: "food-nutrition", label: "Food & Nutrition / Dietetics / Food Technology" },
    { value: "furniture-design", label: "Furniture Design / Carpentry" },
    { value: "graduate-trainee", label: "Graduate Trainee / Fresh Graduate / Graduate Internship" },
    { value: "horticulture-gardening", label: "Horticulture / Beautification / Gardening" },
    { value: "hospitality", label: "Hospitality / Travel & Tourism / Hotel / Restaurant / Catering / Museum / Club / Bar / Tour Guide" },
    { value: "hse-risk-management", label: "HSE / Safety & Risk Management / Compliance" },
    { value: "human-resources", label: "Human Resources / Recruitment" },
    { value: "insurance-actuary", label: "Insurance / Assurance / Actuary" },
    { value: "internship-industrial-training", label: "Internship / SIWES / Industrial Training" },
    { value: "language-translation", label: "Language Translation / Transcribing / Interpreting" },
    { value: "law-legal", label: "Law / Legal" },
    { value: "logistics", label: "Logistics / Procurement / Purchasing / Supply Chain" },
    { value: "maritime-services", label: "Maritime Services / Shipping / Clearing & Forwarding / Marine Officer / Seamen" },
    { value: "marketing-sales", label: "Marketing / Sales / Business Development / Merchandiser" },
    { value: "media-broadcasting", label: "Media / Broadcasting / Journalism / Content Writing / Editing" },
    { value: "medical", label: "Medical" },
    { value: "medical-anatomy", label: "Medical - Anatomy / Physiology / Pathology / Basic Medical Science" },
    { value: "medical-dental", label: "Medical - Dental / ENT" },
    { value: "medical-health-information", label: "Medical - Health Information / Medical Records / Health Management" },
    { value: "medical-nursing", label: "Medical - Nursing & Midwifery" },
    { value: "medical-optometrist", label: "Medical - Optometrist / Ophthalmologist" },
    { value: "medical-pharmaceutical", label: "Medical - Pharmaceutical" },
    { value: "medical-physician", label: "Medical - Physician / Medical Officer / Doctor / Consultants / Medical Internship" },
    { value: "medical-physiotherapy", label: "Medical - Physiotherapy / Massage Therapy / Masseuse / Masseur" },
    { value: "medical-public-health", label: "Medical - Public Health Worker / Hospital Attendant / Orderly" },
    { value: "medical-veterinary", label: "Medical - Veterinary Medicine" },
    { value: "medical-lab", label: "Medical Laboratory / Radiography / Sonography" },
    { value: "modelling", label: "Modelling / Ushering Services / Runway Services" },
    { value: "monitoring-evaluation", label: "Monitoring and Evaluation / Social Worker" },
    { value: "multimedia", label: "Multimedia / Film Production / Photography / Cinematography / Video & Audio Editing" },
    { value: "music-entertainment", label: "Music Entertainment / Comedy / Disc Jockey (DJ) / Master of Ceremony (MC)" },
    { value: "operations-project-management", label: "Operations / Project Management" },
    { value: "physical-sciences", label: "Physical Sciences - Chemistry / Physics / Geography / Earth Science (Geology) / Material Science / Astronomy" },
    { value: "psychology", label: "Psychology / Clinical Psychology" },
    { value: "quality-assurance", label: "Quality Assurance (QA) / Quality Control (QC)" },
    { value: "remote-freelance", label: "Remote / Freelance / Work at home" },
    { value: "research-survey", label: "Research / Survey" },
    { value: "scholarship-grant", label: "Scholarship / Grant / Competition" },
    { value: "security-guard", label: "Security - Guard / Gateman" },
    { value: "security-military", label: "Security - Military / Police / Civil Defence / Para-Military" },
    { value: "security-professional", label: "Security - Professional / Public / Corporate Security Management" },
    { value: "sports-fitness", label: "Sports / Fitness / Gym Instructor" }
];
const jobList = [
    {
        id: "1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed",
        jobTitle: "Software Engineer",
        jobCategory: "IT",
        jobType: "Full-time",
        jobDescription: "Develop and maintain web applications.",
        jobRequirements: "Proficiency in JavaScript and experience with React.",
        locationType: "On-site",
        location: "Lagos, Nigeria",
        salaryRange: "₦3,000,000 - ₦4,000,000/year",
        benefits: "Health insurance, paid time off.",
        applicationDeadline: "2025-02-28",
        applicationInstructions: "Submit your resume and cover letter via email.",
        applicationLink: "careers@techsolutions.com",
        companyName: "Tech Solutions Inc.",
        companyAbout: "A leading tech company specializing in web development.",
        companyWebsite: "https://www.techsolutions.com",
        companyLogo: undefined,
    },
    {
        id: "2a4f6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed",
        jobTitle: "Marketing Manager",
        jobCategory: "Marketing",
        jobType: "Full-time",
        jobDescription: "Lead the marketing team to develop strategies.",
        jobRequirements: "Experience in digital marketing and team management.",
        locationType: "Hybrid",
        location: "Abuja, Nigeria",
        salaryRange: "₦2,500,000 - ₦3,500,000/year",
        benefits: "Flexible working hours, performance bonuses.",
        applicationDeadline: "2025-03-15",
        applicationInstructions: "Apply through our online portal.",
        applicationLink: "https://www.marketingleaders.com/careers",
        companyName: "Marketing Leaders Ltd.",
        companyAbout: "A dynamic marketing agency with a global clientele.",
        companyWebsite: "https://www.marketingleaders.com",
        companyLogo: undefined,
    },
    {
        id: "3c7d8bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed",
        jobTitle: "Data Analyst",
        jobCategory: "Data Analysis",
        jobType: "Contract",
        jobDescription: "Analyze data to support business decisions.",
        jobRequirements: "Strong analytical skills and proficiency in SQL.",
        locationType: "Remote",
        location: undefined,
        salaryRange: "₦1,800,000 - ₦2,200,000/year",
        benefits: "Remote work allowance.",
        applicationDeadline: "2025-02-20",
        applicationInstructions: "Send your portfolio and resume via email.",
        applicationLink: "hr@dataanalytics.com",
        companyName: "Data Analytics Corp.",
        companyAbout: "Specializes in providing data-driven solutions.",
        companyWebsite: "https://www.dataanalytics.com",
        companyLogo: undefined,
    },
    {
        id: "4d9e0bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed",
        jobTitle: "Graphic Designer",
        jobCategory: "Design",
        jobType: "Part-time",
        jobDescription: "Create visual content for various platforms.",
        jobRequirements: "Proficiency in Adobe Creative Suite.",
        locationType: "On-site",
        location: "Port Harcourt, Nigeria",
        salaryRange: "₦1,200,000 - ₦1,500,000/year",
        benefits: "Creative work environment.",
        applicationDeadline: "2025-03-10",
        applicationInstructions: "Submit your portfolio and resume online.",
        applicationLink: "https://www.creativedesigns.com/careers",
        companyName: "Creative Designs Studio",
        companyAbout: "A design studio focused on innovative solutions.",
        companyWebsite: "https://www.creativedesigns.com",
        companyLogo: undefined,
    },
    {
        id: "5e1f2bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed",
        jobTitle: "Sales Executive",
        jobCategory: "Sales",
        jobType: "Full-time",
        jobDescription: "Drive sales and expand market reach.",
        jobRequirements: "Strong communication and negotiation skills.",
        locationType: "On-site",
        location: "Kano, Nigeria",
        salaryRange: "₦2,000,000 - ₦2,800,000/year",
        benefits: "Commission on sales, company car.",
        applicationDeadline: "2025-02-25",
        applicationInstructions: "Apply via our career page.",
        applicationLink: "https://www.salesforce.com/careers",
        companyName: "SalesForce Nigeria",
        companyAbout: "Leading provider of sales solutions.",
        companyWebsite: "https://www.salesforce.com",
        companyLogo: undefined,
    },
    {
        id: "6f3a4bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed",
        jobTitle: "Human Resources Manager",
        jobCategory: "Human Resources",
        jobType: "Full-time",
        jobDescription: "Oversee HR functions and employee relations.",
        jobRequirements: "Experience in HR management and labor laws.",
        locationType: "Hybrid",
        location: "Ibadan, Nigeria",
        salaryRange: "₦2,800,000 - ₦3,500,000/year",
        benefits: "Health benefits, retirement plan.",
        applicationDeadline: "2025-03-05",
        applicationInstructions: "Email your resume and cover letter.",
        applicationLink: "jobs@hrsolutions.com",
        companyName: "HR Solutions Ltd.",
        companyAbout: "Provides comprehensive HR services.",
        companyWebsite: "https://www.hrsolutions.com",
        companyLogo: undefined,
    },
    {
        id: "7g5b6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed",
        jobTitle: "Project Manager",
        jobCategory: "Project Management",
        jobType: "Contract",
        jobDescription: "Manage projects from initiation to closure.",
        jobRequirements: "PMP certification and project management experience.",
        locationType: "Remote",
        location: undefined,
        salaryRange: "₦3,500,000 - ₦4,500,000/year",
        benefits: "Flexible working hours.",
        applicationDeadline: "2025-02-28",
        applicationInstructions: "Apply through our website.",
        applicationLink: "https://www.projectmanagement.com/careers",
        companyName: "Project Management Experts",
        companyAbout: "Specializes in managing large-scale projects.",
        companyWebsite: "https://www.projectmanagement.com",
        companyLogo: undefined,
    },
];
